import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "_/components/ui/sonner"
import Header from "./_components/Header/Header";
import WrapperSessionProvider from "./_components/WrapperSessionProvider/WrapperSessionProvider";
import CartContext from "./_context/CartContext";
import { getUserCart } from "_/api/services/route.services";
import { CartResponse } from "_/api/types";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const res=await getUserCart();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full  flex flex-col ">
        <CartContext res={res as CartResponse}>
    <WrapperSessionProvider>
         <Header/>
        <Navbar/>
        {children}
       <Toaster />
        <Footer/>
        </WrapperSessionProvider>
        </CartContext>
     
      

        </body>
    </html>
  );
}
